Repository importPI19fromDHGE/dhge-pi19-sem3, pull requests merged in 2020-12, with the labels that each got.

#86 RES: rsync, quota, fail2ban
  NET/README.md
  RES/README.md
  RES/pruefungsfragen.md
Labels: documentation

#88 NET: Mitschrifen 30.11.2020
  NET/README.md
  NET/resources/sockets-dgram.png
  NET/resources/sockets-stream.png
Labels: documentation

#85 frontmatter support
  .github/workflows/pandoc.yml
  DBS/README.md
  NET/README.md
  PRO/README.md
  RES/README.md
  SWE/README.md
Labels: P2, enhancement

#94 SWE: Merge 2020.12.03
  NET/README.md
  SWE/README.md
  SWE/resources/Magisches_Dreieck.png
  SWE/resources/magisches-dreieck.png
  SWE/resources/magisches-dreieck.svg
Labels: documentation

#92 SWE-sthinbetween-20201203
  NET/resources/l2-net.png
  NET/resources/l2-net.svg
  NET/resources/nic.png
  NET/resources/nic.svg
  NET/resources/transportschicht.png
  SWE/README.md
  SWE/resources/magisches-dreieck.png
  SWE/resources/magisches-dreieck.svg
Labels: documentation

#90 README: Markdown-Erweiterungen, small Contribution Guide
  README.md
Labels: documentation

#95 Notizen-Merge
  DBS/praktikum/README.md
Labels: documentation

#100 revive sockets.png deleted in 3027966; fixes #99
  NET/resources/sockets.png
Labels: bug, documentation

#97 PRO-sthinbetween-20201204
  PRO/README.md
  PRO/resources/guetefunktion.png
  PRO/resources/guetefunktion2.png
  PRO/resources/neuronales-netz.png
Labels: documentation

#96 Mitschriften SWE 04.12.2020
  SWE/README.md
Labels: documentation

#104 continued where sthinbetween left
  NET/README.md
Labels: documentation

#101 SWE: Oliver 07.12.2020
  NET/resources/l2-net.png
  NET/resources/nic.png
  NET/resources/transportschicht.png
  SWE/README.md
  SWE/resources/function-points-count.png
  SWE/resources/function-points-solution.png
  SWE/resources/uml-class.png
  SWE/resources/uml-diagrams.png
  SWE/resources/uml-objects.png
Labels: documentation

#105 Res max 20201209 2
  RES/README.md
  RES/pruefungsfragen.md
Labels: documentation

#108 SWE-oliver 10.12.2020
  SWE/README.md
  SWE/resources/uml-activity-bsp.png
  SWE/resources/uml-aggregation.png
  SWE/resources/uml-association.png
  SWE/resources/uml-kardinalitäten-bsp.png
  SWE/resources/uml-komposition-bsp.png
  SWE/resources/uml-komposition.png
  SWE/resources/uml-sequenz.png
  SWE/resources/uml-standesbeamter-bsp.png
  SWE/resources/uml-state-mensch.png
  SWE/resources/uml-tiere-bsp.png
Labels: documentation
