Repository importPI19fromDHGE/dhge-pi19-sem3, pull requests merged in 2020-11, with the labels that each got.

#70 Pandoc-Vorbereitung mit AWK: fixes #54
  .github/workflows/pandoc.yml
  DBS/README.md
  DBS/praktikum/README.md
  DBS/praktikum/resources/ERD_Bestandteile.png
  DBS/resources/erm-bsp.png
  NET/README.md
  PRO/README.md
  PRO/resources/it-aufbau.png
  PRO/resources/microservice.png
  RES/README.md
  SWE/README.md
Labels: bug, enhancement

#69 Mitschriften SWE 24.11.2020
  SWE/README.md
Labels: documentation

#74 DBS Grimm vom 25.11.2020
  DBS/praktikum/README.md
  RES/README.md
Labels: documentation

#73 RES: Mitschriften 25.11.2020
  RES/README.md
Labels: documentation

#75 fix pagebreaks, implement newpage and clearpage (fixes #71)
  .github/workflows/pandoc.yml
  DBS/README.md
  DBS/praktikum/README.md
  NET/README.md
  PRO/README.md
  RES/README.md
  SWE/README.md
Labels: P1, bug

#79 NET: radvd / SLAAC Dokumentation mergen
  NET/README.md
Labels: documentation

#80 NET: merge 2020.11.26
  NET/README.md
  NET/resources/Adresstypen.png
  NET/resources/DS_Lite.png
  NET/resources/IPv6_Adresstruktur.png
  NET/resources/IPv6_Header.png
  NET/resources/Raw_Sockets.png
  NET/resources/SLAAC_1.png
  NET/resources/SLAAC_2.png
  NET/resources/Sockets_Stream.png
  NET/resources/TCP.png
  NET/resources/TCP_Options.png
  NET/resources/TCP_Receiving_Congestion.png
  NET/resources/TCP_TCPFO.png
  NET/resources/TCP_Verbindungsaufbau.png
  NET/resources/TCP_Verbindungsaufbau_2.png
  NET/resources/UDP.png
  NET/resources/iso-osi.png
  NET/resources/quic.png
  NET/resources/sockets-stream.png
  NET/resources/sockets.png
  NET/resources/tcp-fastopen.png
  NET/resources/tcp-handshake.png
  NET/resources/tcp-header.png
  NET/resources/tcp-states.png
  NET/resources/tcp-windows.png
  NET/resources/tls-handshake.png
  NET/resources/udp-header.png
Labels: documentation

#78 NET sthinbetween 20201126
  NET/README.md
  NET/resources/Adresstypen.png
  NET/resources/DS_Lite.png
  NET/resources/IPv6_Adresstruktur.png
  NET/resources/IPv6_Header.png
  NET/resources/Raw_Sockets.png
  NET/resources/SLAAC_1.png
  NET/resources/SLAAC_2.png
  NET/resources/Sockets.png
  NET/resources/Transportschicht.png
  NET/resources/iso-osi.png
  NET/resources/quic.png
  NET/resources/sockets-stream.png
  NET/resources/sockets.png
  NET/resources/tcp-fastopen.png
  NET/resources/tcp-handshake.png
  NET/resources/tcp-header.png
  NET/resources/tcp-states.png
  NET/resources/tcp-windows.png
  NET/resources/tls-handshake.png
  NET/resources/udp-header.png
Labels: documentation

#77 DBS Praktikum vom 26.11.2020
  DBS/praktikum/README.md
Labels: documentation

#82 DBS: Some refactoring
  DBS/praktikum/README.md
Labels: documentation

#81 RES: Prüfungsfragen mit Antworten
  RES/pruefungsfragen.md
Labels: documentation

#83 SWE: Mitschriften 30.11.2020
  SWE/README.md
Labels: documentation
