Repository importPI19fromDHGE/dhge-pi19-sem3, pull requests merged in 2021-06, with the labels that each got.

#123 Versuch, PDF Workflow zu reparieren
  SWE-KASCHE/README.md
Labels: bug, documentation

#125 remove mvp from pretotype list
  SWE-KASCHE/README.md
Labels: bug

#127 attempt to fix broken table
  SWE-KASCHE/README.md
Labels: documentation, oopsie
